name: ParaR2

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"

jobs:
  ParaR2:
    uses: TeamKugimiya/reusable-workflows/.github/workflows/ModPack-ParaR2.yml@main
    with:
      para_project_id: "12756"
      para_pack_format: "15"
      para_pack_description: "一個簡單的測試用資源包"
    secrets:
      paratranz_token: ${{ secrets.PARATRANZ_TOKEN }}
      r2_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      r2_access_key: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
      r2_secret_key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
